// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Song;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Song_Roo_Jpa_Entity {
    
    declare @type: Song: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Song.id;
    
    @Version
    @Column(name = "version")
    private Integer Song.version;
    
    public Long Song.getId() {
        return this.id;
    }
    
    public void Song.setId(Long id) {
        this.id = id;
    }
    
    public Integer Song.getVersion() {
        return this.version;
    }
    
    public void Song.setVersion(Integer version) {
        this.version = version;
    }
    
}
