// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.SongIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SongIntegrationTest_Roo_Configurable {
    
    declare @type: SongIntegrationTest: @Configurable;
    
}
