// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Song;
import com.test.domain.SongDataOnDemand;
import com.test.domain.SongIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SongIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SongIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SongIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SongIntegrationTest: @Transactional;
    
    @Autowired
    private SongDataOnDemand SongIntegrationTest.dod;
    
    @Test
    public void SongIntegrationTest.testCountSongs() {
        Assert.assertNotNull("Data on demand for 'Song' failed to initialize correctly", dod.getRandomSong());
        long count = Song.countSongs();
        Assert.assertTrue("Counter for 'Song' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SongIntegrationTest.testFindSong() {
        Song obj = dod.getRandomSong();
        Assert.assertNotNull("Data on demand for 'Song' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Song' failed to provide an identifier", id);
        obj = Song.findSong(id);
        Assert.assertNotNull("Find method for 'Song' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Song' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SongIntegrationTest.testFindAllSongs() {
        Assert.assertNotNull("Data on demand for 'Song' failed to initialize correctly", dod.getRandomSong());
        long count = Song.countSongs();
        Assert.assertTrue("Too expensive to perform a find all test for 'Song', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Song> result = Song.findAllSongs();
        Assert.assertNotNull("Find all method for 'Song' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Song' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SongIntegrationTest.testFindSongEntries() {
        Assert.assertNotNull("Data on demand for 'Song' failed to initialize correctly", dod.getRandomSong());
        long count = Song.countSongs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Song> result = Song.findSongEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Song' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Song' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SongIntegrationTest.testFlush() {
        Song obj = dod.getRandomSong();
        Assert.assertNotNull("Data on demand for 'Song' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Song' failed to provide an identifier", id);
        obj = Song.findSong(id);
        Assert.assertNotNull("Find method for 'Song' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySong(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Song' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SongIntegrationTest.testMergeUpdate() {
        Song obj = dod.getRandomSong();
        Assert.assertNotNull("Data on demand for 'Song' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Song' failed to provide an identifier", id);
        obj = Song.findSong(id);
        boolean modified =  dod.modifySong(obj);
        Integer currentVersion = obj.getVersion();
        Song merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Song' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SongIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Song' failed to initialize correctly", dod.getRandomSong());
        Song obj = dod.getNewTransientSong(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Song' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Song' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Song' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SongIntegrationTest.testRemove() {
        Song obj = dod.getRandomSong();
        Assert.assertNotNull("Data on demand for 'Song' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Song' failed to provide an identifier", id);
        obj = Song.findSong(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Song' with identifier '" + id + "'", Song.findSong(id));
    }
    
}
