// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Song;
import com.test.domain.SongDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SongDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SongDataOnDemand: @Component;
    
    private Random SongDataOnDemand.rnd = new SecureRandom();
    
    private List<Song> SongDataOnDemand.data;
    
    public Song SongDataOnDemand.getNewTransientSong(int index) {
        Song obj = new Song();
        return obj;
    }
    
    public Song SongDataOnDemand.getSpecificSong(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Song obj = data.get(index);
        Long id = obj.getId();
        return Song.findSong(id);
    }
    
    public Song SongDataOnDemand.getRandomSong() {
        init();
        Song obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Song.findSong(id);
    }
    
    public boolean SongDataOnDemand.modifySong(Song obj) {
        return false;
    }
    
    public void SongDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Song.findSongEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Song' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Song>();
        for (int i = 0; i < 10; i++) {
            Song obj = getNewTransientSong(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
